version: '3.8'

services:
  app:
    build:
      context: .
      target: prod  # Use production stage
    environment:
      DATABASE_URL: "postgresql://coredb:db-password@db:5432/coredb"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: coredb
      POSTGRES_PASSWORD: db-password
      POSTGRES_DB: coredb
    volumes:
      - db-data:/hdd/srv/src/db/postgresql/data
  healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      
networks:
  default:
    driver: bridge

volumes:
  db-data:

secrets:
  db-password:
    file: .env